import "./globals.css";
import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={GeistSans.className}>
      <body>
        <main> {children}</main>
      </body>
    </html>
  );
}
